# Robot Start Position
robot_start: 
  - {x: 0.3048, y: -0.3048, z: 0.7286}
  - {x: 0.3048, y: 0.3048,  z: 0.7286}
  - {x: -0.3048, y: 0.3048,  z: 0.7286}
  - {x: -0.3048, y: -0.3048,  z: 0.7286}
  - {x: 0.3048, y: 0.0,  z: 0.7286}
  - {x: -0.3048, y: 0.0,  z: 0.7286}  

# Payload Initial State
payload_start: {x: 0.0, y: 0.0, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}

# Payload Terminal State (Optional)
payload_stop: {x: 0.0, y: 0.0, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}