config_paths:
  # === Default (currently active) ===
  uav_params_path: "uav_params/"
  payload_params_path: "load_params/triangular_payload.yaml"
  mechanism_params_path: "attach_mechanism/cable/3_robots_triangular_payload_1m.yaml"
  payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  uav_control_gain_path: "control_params/"
  number_of_robots: 3
  nmpc_filename: "control_params/payload_nmpc_params.yaml"


  # === Other scenarios (for reference) ===

  # 1. 1 dragonfly with pointmass payload using cable mechanisms (0.5 m)
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/pointmass_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/1_robot_point_mass_0-5m.yaml"
  # payload_control_gain_path: "control_params/pointmass_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 1
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 2. 3 snapdragon with bullnose propeller flights with triangular payload using cable mechanisms (1 m)
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/3_robots_triangular_payload_1m_bullnose_dragonfly.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 3. 3 dragonfly with triangular payload using cable mechanisms (0.5 m)
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/3_robots_triangular_payload_0-5m.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 4. 2 dragonfly with long bar payload using cable mechanisms (0.5 m)
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/long_bar_wood_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/2_robots_long_bar_payload_0-5m.yaml"
  # payload_control_gain_path: "control_params/long_bar_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 2
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 5. 3 dragonfly with triangular payload using cable mechanisms with different cable lengths (2 robots 1m, 1 robot 0.5m)
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/3_robots_triangular_payload_1m_0-5m_different_cable_length.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 6. 3 dragonfly with triangular payload using cable mechanisms with different cable lengths (1.2m, 1m, 0.8m)
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/3_robots_triangular_payload_1-2m_1m_0-8m_different_cable_length.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 7. race, snapdragon, hummingbird with triangular payload using cable mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/3_robots_triangular_payload_1m_different_robots_dynamics.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 8. 4 dragonfly with fedex box payload using cable mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/fedex_box_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/4_robots_fedex_box_0_5m.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 4
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 9. 6 dragonfly with fedex box payload using cable mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/fedex_box_payload.yaml"
  # mechanism_params_path: "attach_mechanism/cable/6_robots_fedex_box_0_5m.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_cable_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 6
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 10. race, snapdragon, hummingbird with triangular payload using rigid link mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/rigid_link/3_hetereogeneous_robots_triangular_payload.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_rigidlink_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 11. 2 dragonfly with long bar payload using rigid link mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/long_bar_wood_payload.yaml"
  # mechanism_params_path: "attach_mechanism/rigid_link/2_robots_long_bar.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_rigidlink_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 2
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 12. 3 dragonfly with triangular payload using rigid link mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/rigid_link/3_robots_triangular_payload.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_rigidlink_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"

  # 13. 3 dragonfly bullnose propeller with triangular payload using rigid link mechanisms
  # uav_params_path: "uav_params/"
  # payload_params_path: "load_params/triangular_payload.yaml"
  # mechanism_params_path: "attach_mechanism/rigid_link/3_robots_triangular_payload_bullnose_dragonfly.yaml"
  # payload_control_gain_path: "control_params/triangular_payload_cooperative_rigidlink_gains.yaml"
  # uav_control_gain_path: "control_params/"
  # number_of_robots: 3
  # nmpc_filename: "control_params/payload_nmpc_params.yaml"
