/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s2[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};

/* payload_model_expl_vde_adj:(i0[13],i1[13],i2[9],i3[22])->(o0[22]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[0]? arg[0][12] : 0;
  a2=5.0000000000000000e-01;
  a3=arg[1]? arg[1][9] : 0;
  a4=(a2*a3);
  a5=(a1*a4);
  a6=arg[0]? arg[0][11] : 0;
  a7=arg[1]? arg[1][8] : 0;
  a8=(a2*a7);
  a9=(a6*a8);
  a5=(a5+a9);
  a9=arg[0]? arg[0][10] : 0;
  a10=arg[1]? arg[1][7] : 0;
  a11=(a2*a10);
  a12=(a9*a11);
  a5=(a5+a12);
  a12=1.;
  a13=arg[0]? arg[0][6] : 0;
  a14=casadi_sq(a13);
  a15=arg[0]? arg[0][7] : 0;
  a16=casadi_sq(a15);
  a14=(a14+a16);
  a16=arg[0]? arg[0][8] : 0;
  a17=casadi_sq(a16);
  a14=(a14+a17);
  a17=arg[0]? arg[0][9] : 0;
  a18=casadi_sq(a17);
  a14=(a14+a18);
  a12=(a12-a14);
  a14=2.;
  a18=arg[1]? arg[1][6] : 0;
  a19=(a14*a18);
  a20=(a12*a19);
  a5=(a5+a20);
  a20=(a13+a13);
  a3=(a14*a3);
  a21=(a17*a3);
  a7=(a14*a7);
  a22=(a16*a7);
  a21=(a21+a22);
  a14=(a14*a10);
  a10=(a15*a14);
  a21=(a21+a10);
  a19=(a13*a19);
  a21=(a21+a19);
  a20=(a20*a21);
  a5=(a5-a20);
  if (res[0]!=0) res[0][6]=a5;
  a5=(a6*a4);
  a20=(a1*a8);
  a5=(a5-a20);
  a14=(a12*a14);
  a5=(a5+a14);
  a2=(a2*a18);
  a18=(a9*a2);
  a5=(a5-a18);
  a18=(a15+a15);
  a18=(a18*a21);
  a5=(a5-a18);
  if (res[0]!=0) res[0][7]=a5;
  a7=(a12*a7);
  a5=(a9*a4);
  a7=(a7-a5);
  a5=(a1*a11);
  a7=(a7+a5);
  a5=(a6*a2);
  a7=(a7-a5);
  a5=(a16+a16);
  a5=(a5*a21);
  a7=(a7-a5);
  if (res[0]!=0) res[0][8]=a7;
  a12=(a12*a3);
  a3=(a9*a8);
  a12=(a12+a3);
  a3=(a6*a11);
  a12=(a12-a3);
  a3=(a1*a2);
  a12=(a12-a3);
  a3=(a17+a17);
  a3=(a3*a21);
  a12=(a12-a3);
  if (res[0]!=0) res[0][9]=a12;
  a12=1.2459788459999999e-02;
  a3=(a12*a1);
  a21=1.5999503580202517e+02;
  a7=arg[1]? arg[1][11] : 0;
  a7=(a21*a7);
  a5=(a3*a7);
  a18=6.2501939200000000e-03;
  a14=(a18*a6);
  a20=8.0258184415435892e+01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a20*a19);
  a19=(a14*a20);
  a5=(a5-a19);
  a19=(a6*a20);
  a10=(a1*a7);
  a19=(a19-a10);
  a19=(a18*a19);
  a5=(a5+a19);
  a19=(a16*a4);
  a5=(a5-a19);
  a19=(a17*a8);
  a5=(a5+a19);
  a19=(a13*a11);
  a5=(a5+a19);
  a19=(a15*a2);
  a5=(a5-a19);
  if (res[0]!=0) res[0][10]=a5;
  a5=(a18*a9);
  a19=(a5*a20);
  a10=arg[1]? arg[1][10] : 0;
  a21=(a21*a10);
  a1=(a1*a21);
  a10=(a9*a20);
  a1=(a1-a10);
  a18=(a18*a1);
  a19=(a19+a18);
  a3=(a3*a21);
  a19=(a19-a3);
  a3=(a15*a4);
  a19=(a19+a3);
  a3=(a13*a8);
  a19=(a19+a3);
  a3=(a17*a11);
  a19=(a19-a3);
  a3=(a16*a2);
  a19=(a19-a3);
  if (res[0]!=0) res[0][11]=a19;
  a14=(a14*a21);
  a5=(a5*a7);
  a14=(a14-a5);
  a9=(a9*a7);
  a6=(a6*a21);
  a9=(a9-a6);
  a12=(a12*a9);
  a14=(a14+a12);
  a13=(a13*a4);
  a14=(a14+a13);
  a15=(a15*a8);
  a14=(a14-a15);
  a16=(a16*a11);
  a14=(a14+a16);
  a17=(a17*a2);
  a14=(a14-a17);
  if (res[0]!=0) res[0][12]=a14;
  a14=3.5971223021582732e+00;
  a17=arg[1]? arg[1][3] : 0;
  a17=(a14*a17);
  if (res[0]!=0) res[0][13]=a17;
  a17=arg[1]? arg[1][4] : 0;
  a17=(a14*a17);
  if (res[0]!=0) res[0][14]=a17;
  a17=arg[1]? arg[1][5] : 0;
  a14=(a14*a17);
  if (res[0]!=0) res[0][15]=a14;
  if (res[0]!=0) res[0][16]=a21;
  if (res[0]!=0) res[0][17]=a7;
  if (res[0]!=0) res[0][18]=a20;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int payload_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real payload_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
