N : 10
Tf : 1.0
pl_max_vel : [10,10,10] #max linear velocity
pl_min_vel : [-10,-10,-10] 
pl_max_omega : [10,10,10 ]   #rad/s for RPY
pl_min_omega : [-10,-10,-10]

dist_r : 0.0
dist_OL  : 0.0
dist_Or : 0.0





