obstacles: 
  wall1 : {x: 0.25,y : 1.517, z: 3.5, l: 5.5, b: 0.5, h: 2.0}
  # wall1 : {x: -3.5,y : 1.267, z: 0, l: 5.5, b: 0.5, h: 2}
  # wall2 : {x: 0,y : -1, z: 0, l: 1.0, b: 0.95, h: 10 }
  # wall3 : {x: 0,y : 1 , z: 0, l: 1.0, b: 0.95, h: 10 }
  # wall4 : {x: -2.25,y : 1.6, z: 0, l: 5.5, b: 0.5, h: 10 }